### ISSUE TITLE
Error running fedbox with `FEDBOX_ENV=dev`

### ISSUE THREAD

**Issue by bekriebel** [go-ap/fedbox#10]
After building, when you attempt to run `./bin/fedbox`, an error is generated:

```
panic: chi: attempting to Mount() a handler on an existing path, '/debug'

goroutine 1 [running]:
github.com/go-chi/chi/v5.(*Mux).Mount(0xc0000b2ba0, {0xecae61, 0x6}, {0x1058280, 0xc0000b33e0?})
        /home/[redacted]/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/mux.go:292 +0x445
github.com/go-ap/fedbox.New({0x1061e10, 0xc0003c21c0}, {0x1055108, 0xe}, {{0xc0001491cb, 0x3}, 0x1, {0x0, 0x0}, 0x37e11d600, ...}, ...)
        /home/[redacted]/src/fedbox/app.go:146 +0x110f
github.com/go-ap/fedbox/internal/cmd.run.func1(0xc00031c780?)
        /home/[redacted]/src/fedbox/internal/cmd/fedbox.go:75 +0x5d8
github.com/urfave/cli/v2.(*Command).Run(0xc00031c780, 0xc0003c4d40, {0xc0000ae1e0, 0x1, 0x1})
        /home/[redacted]/go/pkg/mod/github.com/urfave/cli/v2@v2.23.6/command.go:271 +0xa82
github.com/urfave/cli/v2.(*App).RunContext(0xc0003c8000, {0x105d7b0?, 0xc0000d40c8}, {0xc0000ae1e0, 0x1, 0x1})
        /home/[redacted]/go/pkg/mod/github.com/urfave/cli/v2@v2.23.6/app.go:333 +0x665
github.com/urfave/cli/v2.(*App).Run(...)
        /home/[redacted]/go/pkg/mod/github.com/urfave/cli/v2@v2.23.6/app.go:310
main.main()
        /home/[redacted]/src/fedbox/cmd/fedbox/main.go:16 +0xc5
```

This can be fixed by setting the `FEDBOX_ENV` to something other than `dev` or by reverting commit 5f1a7491e010ecd0fc4597977831f63963bd4283.

**Comment by mariusor** [comment]
Hi @bekriebel, this has been fixed some time ago, apologies for taking this long to get back to you. :)

I hope you managed to work your way around the issue. The profiling end-points are not really used, I should probably remove them all together.
